name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      working-directory: WebApplication1
      run: dotnet restore
    - name: Build
      working-directory: WebApplication1
      run: dotnet build --no-restore
      
    - name: Build and push Docker images
      uses: docker/build-push-action@v2.7.0

